public with sharing class AdderHelper {
    // Method to add two numbers
    public static Integer addNumbers(Integer a, Integer b) {
        return a + b;
    }
    //Method to add three numbers
    public static Integer addNum(Integer a, Integer b, Integer c) {
        return a + b + c;
    }
    //Method to multiply two numbers
     public static Integer multiplyNum(Integer a, Integer b, Integer c) {
        return a*b*c;
    }
    //Method to divide two numbers 
     public static Integer divNum(Integer a, Integer b) {
        return a/b;
    }
}