public with sharing class DemoHandler {
    public static Integer InDemoHandler(Integer a, Integer b, Integer c) {
     return a+b+c;
    }
    public static Integer addNum(Integer a, Integer b, Integer c,Integer d) {
     return a+b+c+d;
    }
        public static Integer subNum(Integer a, Integer b) {
    return a-b;
    }
     public static Integer divNum(Integer a, Integer b) {
     return a/b;
    }
}